Complete minimal implementation
Sadere/gophkeeper pull request #5
Opened 2024-08-22 20:06 UTC by Sadere

2024-09-01 13:11 UTC, arttet requested changes

2024-09-02 09:34 UTC, Sadere commented on proto/keeper/v1/secrets.proto
> +message DownloadFileV1Request {
fixed

2024-09-10 15:51 UTC, arttet approved these changes
Good job!

2024-09-10 15:51 UTC, arttet commented on docker/Dockerfile
> +FROM golang:1.22.4
You need to use multi-stages build.
https://docs.docker.com/build/building/multi-stage/

2024-09-10 15:51 UTC, arttet commented on internal/client/api/client.go
> +//go:generate mockgen -source client.go -destination mocks/mock_client.go -package api
It would be better if it was in the `mockgen` package.

2024-09-10 15:51 UTC, arttet commented on internal/client/api/grpc/notification.go
> +	time.Sleep(time.Second * 2)
This is a magic number

2024-10-02 17:12 UTC, merged